"""empty message

Revision ID: 41f7c4b95934
Revises: 536e165d8fe2
Create Date: 2026-03-08 04:18:05.056673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41f7c4b95934'
down_revision: Union[str, None] = '536e165d8fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_document_chunks_filename'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('idx_channel_status'), table_name='conversations')
    op.drop_index(op.f('idx_customer_status'), table_name='conversations')
    op.drop_index(op.f('idx_intent'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_intent'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_ticket_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_id'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_question'), table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('idx_conversation_created'), table_name='messages')
    op.drop_index(op.f('idx_conversation_intent'), table_name='messages')
    op.drop_index(op.f('idx_requires_human'), table_name='messages')
    op.drop_index(op.f('idx_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_intent'), table_name='messages')
    op.drop_index(op.f('ix_messages_requires_human'), table_name='messages')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('idx_active_vip'), table_name='customers')
    op.drop_index(op.f('idx_customer_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_vip'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Customer first name'),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Customer last name'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Customer email address (unique)'),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Customer phone number'),
    sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='External customer ID from core banking system'),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Primary account number'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether customer account is active'),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether customer identity is verified'),
    sa.Column('is_vip', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='VIP customer flag (premium service)'),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Bcrypt hashed password'),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="RBAC Role: 'user', 'admin', 'auditor'"),
    sa.Column('scopes', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment="Space-separated permissions e.g. 'read:accounts write:transfer'"),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Internal notes about customer'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('ix_customers_is_vip'), 'customers', ['is_vip'], unique=False)
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('idx_customer_name'), 'customers', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('idx_active_vip'), 'customers', ['is_active', 'is_vip'], unique=False)
    op.create_table('transactions',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('merchant_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('transactions_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Foreign key to conversation'),
    sa.Column('role', postgresql.ENUM('CUSTOMER', 'AGENT', 'SYSTEM', 'HUMAN_AGENT', name='messagerole'), autoincrement=False, nullable=False, comment='Message sender role'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='Message content/text'),
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Name of AI agent that generated message (if role=agent)'),
    sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Detected intent in customer message'),
    sa.Column('sentiment', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Message sentiment (positive, negative, neutral)'),
    sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True, comment='Confidence score (0-100) for intent detection'),
    sa.Column('is_error', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether message represents an error'),
    sa.Column('requires_human', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether message requires human agent intervention'),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True, comment='Additional metadata as JSON string'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_requires_human'), 'messages', ['requires_human'], unique=False)
    op.create_index(op.f('ix_messages_intent'), 'messages', ['intent'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('idx_requires_human'), 'messages', ['requires_human'], unique=False)
    op.create_index(op.f('idx_conversation_intent'), 'messages', ['conversation_id', 'intent'], unique=False)
    op.create_index(op.f('idx_conversation_created'), 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('faqs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('faqs_pkey'))
    )
    op.create_index(op.f('ix_faqs_question'), 'faqs', ['question'], unique=False)
    op.create_index(op.f('ix_faqs_id'), 'faqs', ['id'], unique=False)
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='savings, credit, loan'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='Annual interest rate (decimal)'),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of product features'),
    sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Eligibility requirements'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_table('conversations',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Foreign key to customer'),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='Conversation title/subject'),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'RESOLVED', 'ESCALATED', 'CLOSED', name='conversationstatus'), autoincrement=False, nullable=False, comment='Current conversation status'),
    sa.Column('channel', postgresql.ENUM('WEB', 'MOBILE', 'API', 'WHATSAPP', 'SMS', name='conversationchannel'), autoincrement=False, nullable=False, comment='Communication channel'),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True, comment='AI-generated conversation summary'),
    sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Detected customer intent'),
    sa.Column('sentiment', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Overall conversation sentiment'),
    sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Total number of messages'),
    sa.Column('escalation_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Reason for escalation (if escalated)'),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Priority of escalation (if escalated)'),
    sa.Column('ticket_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('conversations_customer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('ix_conversations_ticket_id'), 'conversations', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_intent'), 'conversations', ['intent'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_channel'), 'conversations', ['channel'], unique=False)
    op.create_index(op.f('idx_intent'), 'conversations', ['intent'], unique=False)
    op.create_index(op.f('idx_customer_status'), 'conversations', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('idx_channel_status'), 'conversations', ['channel', 'status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.create_index(op.f('ix_document_chunks_filename'), 'document_chunks', ['filename'], unique=False)
    op.create_table('accounts',
    sa.Column('account_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='External Link'),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('CURRENT', 'SAVINGS', 'LOAN', 'CREDIT', name='accounttype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'FROZEN', 'CLOSED', name='accountstatus'), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('available_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('accounts_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    # ### end Alembic commands ###
