"""add_faq_table

Revision ID: 536e165d8fe2
Revises: f57c936ded09
Create Date: 2026-01-18 03:38:38.172294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536e165d8fe2'
down_revision: Union[str, None] = 'f57c936ded09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_faqs_category', table_name='faqs')
    op.drop_index('ix_faqs_id', table_name='faqs')
    op.drop_index('ix_faqs_question', table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='faqs_pkey')
    )
    op.create_index('ix_faqs_question', 'faqs', ['question'], unique=False)
    op.create_index('ix_faqs_id', 'faqs', ['id'], unique=False)
    op.create_index('ix_faqs_category', 'faqs', ['category'], unique=False)
    # ### end Alembic commands ###
