"""Initial migration: create customers, conversations, messages tables

Revision ID: f57c936ded09
Revises: 
Create Date: 2025-12-14 18:31:52.625606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57c936ded09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Customer first name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Customer last name'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Customer email address (unique)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Customer phone number'),
    sa.Column('customer_id', sa.String(length=50), nullable=False, comment='External customer ID from core banking system'),
    sa.Column('account_number', sa.String(length=50), nullable=True, comment='Primary account number'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether customer account is active'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether customer identity is verified'),
    sa.Column('is_vip', sa.Boolean(), nullable=False, comment='VIP customer flag (premium service)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about customer'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_vip', 'customers', ['is_active', 'is_vip'], unique=False)
    op.create_index('idx_customer_name', 'customers', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.create_index(op.f('ix_customers_is_vip'), 'customers', ['is_vip'], unique=False)
    op.create_table('conversations',
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Foreign key to customer'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Conversation title/subject'),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'ESCALATED', 'CLOSED', name='conversationstatus'), nullable=False, comment='Current conversation status'),
    sa.Column('channel', sa.Enum('WEB', 'MOBILE', 'API', 'WHATSAPP', 'SMS', name='conversationchannel'), nullable=False, comment='Communication channel'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI-generated conversation summary'),
    sa.Column('intent', sa.String(length=100), nullable=True, comment='Detected customer intent'),
    sa.Column('sentiment', sa.String(length=50), nullable=True, comment='Overall conversation sentiment'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='Total number of messages'),
    sa.Column('escalation_reason', sa.Text(), nullable=True, comment='Reason for escalation (if escalated)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_status', 'conversations', ['channel', 'status'], unique=False)
    op.create_index('idx_customer_status', 'conversations', ['customer_id', 'status'], unique=False)
    op.create_index('idx_intent', 'conversations', ['intent'], unique=False)
    op.create_index(op.f('ix_conversations_channel'), 'conversations', ['channel'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_intent'), 'conversations', ['intent'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='Foreign key to conversation'),
    sa.Column('role', sa.Enum('CUSTOMER', 'AGENT', 'SYSTEM', 'HUMAN_AGENT', name='messagerole'), nullable=False, comment='Message sender role'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content/text'),
    sa.Column('agent_name', sa.String(length=100), nullable=True, comment='Name of AI agent that generated message (if role=agent)'),
    sa.Column('intent', sa.String(length=100), nullable=True, comment='Detected intent in customer message'),
    sa.Column('sentiment', sa.String(length=50), nullable=True, comment='Message sentiment (positive, negative, neutral)'),
    sa.Column('confidence_score', sa.Integer(), nullable=True, comment='Confidence score (0-100) for intent detection'),
    sa.Column('is_error', sa.Boolean(), nullable=False, comment='Whether message represents an error'),
    sa.Column('requires_human', sa.Boolean(), nullable=False, comment='Whether message requires human agent intervention'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='Additional metadata as JSON string'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_conversation_intent', 'messages', ['conversation_id', 'intent'], unique=False)
    op.create_index('idx_requires_human', 'messages', ['requires_human'], unique=False)
    op.create_index('idx_role', 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_intent'), 'messages', ['intent'], unique=False)
    op.create_index(op.f('ix_messages_requires_human'), 'messages', ['requires_human'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_requires_human'), table_name='messages')
    op.drop_index(op.f('ix_messages_intent'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_role', table_name='messages')
    op.drop_index('idx_requires_human', table_name='messages')
    op.drop_index('idx_conversation_intent', table_name='messages')
    op.drop_index('idx_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_intent'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel'), table_name='conversations')
    op.drop_index('idx_intent', table_name='conversations')
    op.drop_index('idx_customer_status', table_name='conversations')
    op.drop_index('idx_channel_status', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_customers_is_vip'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_index('idx_customer_name', table_name='customers')
    op.drop_index('idx_active_vip', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
